version: '3.8'
services:
  courses-db:
    image: postgres:13
    container_name: courses_db
    environment:
      POSTGRES_DB: courses_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: course_management_backend
    container_name: course_management_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://courses-db:5432/courses_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.xml
    depends_on:
      - courses-db

volumes:
  pgdata:
